// Web/Web-ReactSDK/src/components/Navbar.tsx
import { Disclosure } from "@headlessui/react";
import { Bars3Icon, XMarkIcon } from "@heroicons/react/24/outline";
import { Link } from "react-router-dom";

const navigation = [
  { name: "Home", href: "/", current: true },
  { name: "Schedule a Meeting", href: "/schedule-meeting", current: false },
  { name: "Join Meeting", href: "/join-meeting", current: false },
];

function classNames(...classes: any[]) {
  return classes.filter(Boolean).join(" ");
}

export default function Navbar() {
  return (
    <div>
      <Disclosure as="nav" className="bg-gray-800 fixed w-screen top-0 z-50">
        {({ open }) => (
          <>
            <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
              <div className="relative flex h-16 items-center justify-between">
                <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
                  {/* Mobile menu button*/}
                  <Disclosure.Button className="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
                    <span className="sr-only">Open main menu</span>
                    {open ? (
                      <XMarkIcon className="block h-6 w-6" aria-hidden="true" />
                    ) : (
                      <Bars3Icon className="block h-6 w-6" aria-hidden="true" />
                    )}
                  </Disclosure.Button>
                </div>
                <div className="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                  <div className="flex flex-shrink-0 items-center">
                    <img
                      className="block h-8 w-auto lg:hidden"
                      src="https://meethour.io/images/logo.SVG"
                      alt="Your Company"
                    />
                    <img
                      className="hidden h-8 w-auto lg:block"
                      src="https://meethour.io/images/logo.SVG"
                      alt="Your Company"
                    />
                  </div>
                  <div className="hidden sm:ml-6 sm:block">
                    <div className="flex space-x-4">
                      {navigation.map((item) => {
                        return (
                          <div
                            key={item.name}
                            className={classNames(
                              item.current
                                ? "bg-gray-900 text-white"
                                : "text-gray-300 hover:bg-gray-700 hover:text-white",
                              "px-3 py-2 rounded-md text-sm font-medium"
                            )}
                            aria-current={item.current ? "page" : undefined}
                          >
                            <Link to={item.href}>{item.name}</Link>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <Disclosure.Panel className="sm:hidden">
              <div className="space-y-1 px-2 pt-2 pb-3">
                {navigation.map((item) => (
                  <Disclosure.Button
                    key={item.name}
                    as="a"
                    href={item.href}
                    className={classNames(
                      item.current
                        ? "bg-gray-900 text-white"
                        : "text-gray-300 hover:bg-gray-700 hover:text-white",
                      "block px-3 py-2 rounded-md text-base font-medium"
                    )}
                    aria-current={item.current ? "page" : undefined}
                  >
                    {item.name}
                  </Disclosure.Button>
                ))}
              </div>
            </Disclosure.Panel>
          </>
        )}
      </Disclosure>
    </div>
  );
}

// Web/Javascript/Angular/src/app/components/navbar/navbar.component.ts
import { CommonModule, NgFor } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

interface NavigationItem {
  name: string;
  href: string;
  current: boolean;
}

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
  standalone: true,
  imports: [NgFor, CommonModule, RouterModule]
})
export class NavbarComponent {
  navigation: NavigationItem[] = [
    { name: 'Home', href: '/', current: true },
    { name: 'Schedule a Meeting', href: '/schedule-meeting', current: false },
    { name: 'Join Meeting', href: '/join-meeting', current: false }
  ];
  isMenuOpen: boolean = false;

  classNames(...classes: string[]): string {
    console.log(classes.filter(Boolean).join(' '), 'classNames===');
    return classes.filter(Boolean).join(' ');
  }
  toggleMenu() {
    this.isMenuOpen = !this.isMenuOpen
  }
}

<div>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-content">
        <button class="menu-button" (click)="toggleMenu()">
          <span class="sr-only">Open main menu</span>
          <svg *ngIf="isMenuOpen" class="icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M6 18L18 6M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <svg *ngIf="!isMenuOpen" class="icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M4 6h16M4 12h16m-7 6h7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </button>
        <div class="logo">
          <a routerLink="/">
            <img src="https://meethour.io/images/logo.SVG" alt="Your Company" class="logo-img">
          </a>
        </div>
        <div class="nav-links">
          <div *ngFor="let item of navigation" [ngClass]="classNames('nav-link', item.current ? 'current' : '')">
            <a [routerLink]="item.href" style="color: aliceblue; text-decoration: none;">{{ item.name }}</a>
          </div>
        </div>
      </div>
    </div>
    <div class="mobile-menu" *ngIf="isMenuOpen">
      <div *ngFor="let item of navigation" [ngClass]="classNames('mobile-nav-link', item.current ? 'current' : '')">
        <a [routerLink]="item.href" (click)="toggleMenu()">{{ item.name }}</a>
      </div>
    </div>
  </nav>
</div>
<!-- The routed views render in the <router-outlet> -->
<router-outlet></router-outlet>
