// Web/Javascript/React/src/components/ScheduleMeetingForm.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable array-callback-return */
/* eslint-disable max-len */
/* eslint-disable camelcase */
import ApiServices, { ScheduleMeetingType, UserObjectType } from 'meet-hour-react-web-sdk';
import moment from 'moment';
import MomentTimezone from 'moment-timezone';
import React, { useContext, useState } from 'react';

import { AppContext } from '../App';

import Dropdown from './Dropdown';
import LottieComponent from './LottieComponent';
import Timezone from './Timezone';


interface PropsType {
  addModerator: (value: number) => void;
  addParticipant: (value: number | UserObjectType) => void;
  inputChangeHandler: (value: any) => void;
  isLoading: boolean;
  onSubmitHandler: () => void;
  popupFields: any;
  removeModerator: (value: number) => void;
  removeParticipant: (value: number | UserObjectType) => void;
  requestBody: ScheduleMeetingType;
  setIsLoading: (value: boolean) => void;
  setOpen: (value: boolean) => void;
  setPopupFields: (value: any) => void;
  setRequestBody: (value: ScheduleMeetingType) => void;
}

/**
 @returns {Promise<Array<string>>}
 */
async function getUser(): Promise<Array<string>> {
    const response = await ApiServices.userDetails(
    localStorage.getItem('accessToken') || ''
    );

    return [ response.data.name, response.data.email ];
}
const instantMeeting = async (
        setOpen: (value: boolean) => void,
        setPopupFields: (value: any) => void,
        setIsLoading: (value: boolean) => void,
        setIsInstant: (value: boolean) => void,
        appContext: any
// eslint-disable-next-line max-params
) => {
    let response;
    try {
        setIsInstant(true);
        setIsLoading(true);
        const [ name, email ] = await getUser();
        const host = {
            first_name: name?.split(' ')[0],
            last_name: name?.split(' ')[1],
            email
        };
        const body = {
            meeting_name: 'Quick Meeting',
            agenda: '',
            passcode: '123456',
            meeting_date: moment().format('DD-MM-YYYY'),
            meeting_time: moment().format('hh:mm'),
            meeting_meridiem: moment().format('h:mm a')
.split(' ')[1].toUpperCase(),
            timezone: MomentTimezone.tz.guess(),
            instructions: 'Team call, join as soon as possible',
            is_show_portal: 0,
            options: [ 'ALLOW_GUEST', 'JOIN_ANYTIME' ],
            hostusers: [ host ]
        };
        response = await ApiServices.scheduleMeeting(
      localStorage.getItem('accessToken') || '',
      body
        );

        if (response.success) {
            setOpen(true);
            setPopupFields({
                meeting_id: response.data.meeting_id,
                passcode: response.data.passcode,
                joinURL: response.data.joinURL
            });
            localStorage.setItem('meetingId', response.data.meeting_id);
            localStorage.setItem('pCode', response.data.pcode);
        }
    } catch (error) {
        appContext.setIsError(true);
        appContext.setErrorMessage(response.message)
        console.log(error);
    } finally {
        setIsLoading(false);
    }
};

const AddContactForm = ({
    addParticipant
}: {
addParticipant: (value: UserObjectType) => void;
}) => {
    const [ userContact, setUserContact ] = useState<UserObjectType>({
        first_name: '',
        last_name: '',
        email: ''
    });

    return (
        <div className="grid gap-2 mt-2">
            <div>
                <label className="sr-only">First Name</label>
                <input
                    onChange={e => {
                        const body = {
                            first_name: e.target.value,
                            last_name: userContact.last_name,
                            email: userContact.email
                        };

                        setUserContact(body);
                    }}
                    type="text"
                    className="appearance-none rounded-none relative block
                w-full px-3 py-2 border border-gray-300
                placeholder-gray-500 text-gray-900 rounded-b-md
                focus:outline-none focus:ring-indigo-500
                focus:border-indigo-500 focus:z-10 sm:text-sm"
                    placeholder="First Name"
                />
            </div>
            <div>
                <label className="sr-only">Last Name</label>
                <input
                    onChange={e => {
                        const body = {
                            first_name: userContact.first_name,
                            last_name: e.target.value,
                            email: userContact.email
                        };

                        setUserContact(body);
                    }}
                    type="text"
                    className="appearance-none rounded-none relative block
                w-full px-3 py-2 border border-gray-300
                placeholder-gray-500 text-gray-900 rounded-b-md
                focus:outline-none focus:ring-indigo-500
                focus:border-indigo-500 focus:z-10 sm:text-sm"
                    placeholder="Last Name"
                />
            </div>
            <div>
                <label className="sr-only">Email</label>
                <input
                    onChange={e => {
                        const body = {
                            first_name: userContact.first_name,
                            last_name: userContact.last_name,
                            email: e.target.value
                        };

                        setUserContact(body);
                    }}
                    type="email"
                    className="appearance-none rounded-none relative block
                w-full px-3 py-2 border border-gray-300
                placeholder-gray-500 text-gray-900 rounded-b-md
                focus:outline-none focus:ring-indigo-500
                focus:border-indigo-500 focus:z-10 sm:text-sm"
                    placeholder="Email"
                />
            </div>
            <button
                onClick={event => {
                    event.preventDefault();
                    addParticipant(userContact);
                }}
                className="px-5 py-2 border border-blue-500 rounded-md"
            >
      Add
            </button>
        </div>
    );
};


/**
 @returns {JSX}
 */
function ScheduleMeetingForm(props: PropsType) {
    const [ isInstant, setIsInstant ] = useState<boolean>(false);
    const [ contacts, setContacts ] = useState<Array<any>>([]);
    const appContext = useContext(AppContext);
    const getContactsList = async () => {
        if (!localStorage.getItem('accessToken')) {
            return;
        }
        const body = {
            limit: 0,
            page: 0,
            exclude_hosts: 0
        };
        let response;
        try {
            response = await ApiServices.contactsList(
        localStorage.getItem('accessToken') || '',
        body
            );
            setContacts(response.contacts);
        } catch (error) {
            console.log(error);
            appContext?.setIsError(true);
            appContext?.setErrorMessage(response.message)
            setTimeout(() => {
                appContext?.setIsError(false);
            }, 3000);
        }
    };

    React.useEffect(() => {
        getContactsList();
    }, []);

    return (

        <div className="flex min-h-full items-center justify-center lg:w-[40%] pb-6 px-4 sm:px-3 lg:px-4 ml-3">
            <div className="w-full max-w-sm space-y-8">
            <form onSubmit={(event) => {
                            event.preventDefault()
                            setIsInstant(false);
                                props.onSubmitHandler();
                        }} id="scheduleform">
                <div>
                    <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
            Schedule a meeting
                    </h2>
                </div>
                <div className="mt-8 space-y-6">
                    <input type="hidden" name="remember" defaultValue="true" />
                    <div className="-space-y-px rounded-md shadow-sm grid gap-5">
                        <div>
                            <label htmlFor="meeting_name" className="sr-only">
                Meeting Name
                            </label>
                            <input
                                onChange={e => {
                                    props.inputChangeHandler(e);
                                }}
                                id="meeting_name"
                                name="meeting_name"
                                type="text"
                                required
                                className="appearance-none rounded-none relative block
                  w-full px-3 py-2 border border-gray-300
                  placeholder-gray-500 text-gray-900 rounded-b-md
                  focus:outline-none focus:ring-indigo-500
                  focus:border-indigo-500 focus:z-10 sm:text-sm"
                                placeholder="Meeting Name"
                            />
                        </div>
                        <div>
                            <label htmlFor="passcode" className="sr-only">
                Passcode
                            </label>
                            <input
                                onChange={e => {
                                    props.inputChangeHandler(e);
                                }}
                                id="passcode"
                                name="passcode"
                                type="text"
                                required
                                className="appearance-none rounded-none relative block
                  w-full px-3 py-2 border border-gray-300
                  placeholder-gray-500 text-gray-900 rounded-b-md
                  focus:outline-none focus:ring-indigo-500
                  focus:border-indigo-500 focus:z-10 sm:text-sm"
                                placeholder="Passcode"
                            />
                        </div>
                        <div>
                            <label htmlFor="meeting_date" className="sr-only">
                Meeting Date
                            </label>
                            <input
                                onChange={e => {
                                    props.inputChangeHandler(e);
                                }}
                                id="meeting_date"
                                name="meeting_date"
                                type="date"
                                required
                                className="appearance-none rounded-none relative block
                  w-full px-3 py-2 border border-gray-300
                  placeholder-gray-500 text-gray-900 rounded-b-md
                  focus:outline-none focus:ring-indigo-500
                  focus:border-indigo-500 focus:z-10 sm:text-sm"
                                placeholder="Meeting Name"
                            />
                        </div>
                        <div>
                            <label htmlFor="meeting_time" className="sr-only">
                Meeting Time
                            </label>
                            <input
                                onChange={e => {
                                    props.inputChangeHandler(e);
                                }}
                                id="meeting_time"
                                name="meeting_time"
                                type="time"
                                required
                                className="appearance-none rounded-none relative block
                  w-full px-3 py-2 border border-gray-300
                  placeholder-gray-500 text-gray-900 rounded-b-md
                  focus:outline-none focus:ring-indigo-500
                  focus:border-indigo-500 focus:z-10 sm:text-sm"
                                placeholder="Meeting Name"
                            />
                        </div>
                        <Timezone requestBody={props.requestBody} setRequestBody={props.setRequestBody} inputChangeHandler={props.inputChangeHandler} />
                        <Dropdown
                            isModeratorType={false}
                            contacts={contacts}
                            addParticipant={props.addParticipant}
                        />
                        {props.requestBody.attend?.map((user: any) => {
                            if (typeof user !== 'number') {
                                return (
                                    <div className="flex justify-between">
                                        <h1>{user.first_name}</h1>
                                        <button
                                            className="border border-slate-400 rounded-md px-3"
                                            onClick={() => {
                                                props.removeParticipant(user);
                                            }}
                                        >
                      Remove
                                        </button>
                                    </div>
                                );
                            }
                        })}
                        {contacts?.map((user: any) => {
                            if (props.requestBody.attend?.includes(user.id) === false) {
                                return null;
                            }

                            return (
                                <div className="flex justify-between">
                                    <h1>{user.first_name}</h1>
                                    <button
                                        className="border border-slate-400 rounded-md px-3"
                                        onClick={() => {
                                            props.removeParticipant(user.id);
                                        }}
                                    >
                    Remove
                                    </button>
                                </div>
                            );
                        })}
                        <div>
                            <h1 className="text-lg font-semibold">
                Add participant manually
                            </h1>
                            <AddContactForm addParticipant={props.addParticipant} />
                        </div>
                        <Dropdown
                            isModeratorType={true}
                            contacts={contacts}
                            addModerator={props.addModerator}
                        />
                        {contacts.map((user: any) => {
                            if (props.requestBody.hostusers?.includes(user.id) === false) {
                                return null;
                            }

                            return (
                                <div className="flex justify-between">
                                    <h1>{user.first_name}</h1>
                                    <button
                                        className="border border-slate-400 rounded-md px-3"
                                        onClick={() => {
                                            props.removeModerator(user.id);
                                        }}
                                    >
                    Remove
                                    </button>
                                </div>
                            );
                        })}
                        <div className="">
                            <p className="mt-3 text-sm">General Options</p>
                            <div className="flex items-start mt-2">
                                <div className="flex h-5 items-center">
                                    <input
                                        onChange={e => {
                                            props.inputChangeHandler(e);
                                        }}
                                        id="options"
                                        name="options"
                                        type="checkbox"
                                        value="ALLOW_GUEST"
                                        className="h-4 w-4 rounded text-indigo-600 focus:ring-indigo-500"
                                    />
                                </div>
                                <div className="ml-3 text-sm">
                                    <label
                                        htmlFor="options"
                                        className="font-medium text-gray-700"
                                    >
                    Guest user can join meeting
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div>
                        <button
                        type='submit'
                            className="group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                        >
                            <span className="absolute inset-y-0 left-0 flex items-center pl-3"></span>
                            {props.isLoading && !isInstant
                                ? <LottieComponent />
                                : 'Schedule a meeting'
                            }
                        </button>
                    </div>
                </div>
                </form>
                <div className="flex justify-center">
                            <h1 className="my-3">Or</h1>
                        </div>
                        <button
                            onClick={() => {
                                instantMeeting(
                  props.setOpen,
                  props.setPopupFields,
                  props.setIsLoading,
                  setIsInstant,
                  appContext
                                );
                            }}
                            className="group relative flex w-full justify-center rounded-md border border-transparent bg-violet-600 py-2 px-4 text-sm font-medium text-white hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2"
                        >
                            {props.isLoading && isInstant
                                ? <LottieComponent />
                                : 'Start Instant Meeting'
                            }
                        </button>
            </div>
        </div>    );
}


export default ScheduleMeetingForm;

// Web/Javascript/Angular/src/app/components/schedule-meeting-form/schedule-meeting-form.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { ApiService, ScheduleMeetingType, UserObjectType } from 'angular-meethour';
import moment from 'moment';
import * as MomentTimezone from 'moment-timezone';
import { TimezoneComponent } from '../../timezone/timezone.component';
import { CommonModule, NgFor } from '@angular/common';
import { FormControl, FormsModule, NgModel } from '@angular/forms';

@Component({
  selector: 'app-schedule-meeting-form',
  templateUrl: './schedule-meeting-form.component.html',
  styleUrls: ['./schedule-meeting-form.component.css'],
  imports: [TimezoneComponent, NgFor, FormsModule, CommonModule],
  standalone: true
})
export class ScheduleMeetingFormComponent implements OnInit {
  isLoading: boolean = false;
  isScheduleLoading: boolean = false;
  isInstantLoading: boolean = false;
  isFormLoading: boolean = false;
  showModal: boolean = false;
  roomName = "";
  passcode = "";
  joinURL = "";
  @Input() requestBody: any = {
    meeting_name: '',
    passcode: '',
    meeting_date: '',
    meeting_time: '',
    timezone: '',
    instructions: '',
    is_show_portal: 1,
    options: [],
    hostusers: [],
    meeting_meridiem: '',
    attend: []
  };
  @Input() userObject: any = { first_name: "", last_name: "", email: "" }
  @Input() popupFields: any;
  @Input() contacts: any = [];
  selectedModeratorContact: any;
  selectedParticipantContact: any;
  isInstant: boolean = false;
  isModeratorType: boolean = false;

  @Output() setRequestBody = new EventEmitter<any>();

  constructor(private apiService: ApiService) { }

  ngOnInit() {
    this.getContactsList();
  }

  showToast(messageType: string) {
    var toast = document.getElementById(messageType);
    toast?.classList.add("show");
    setTimeout(function() {
      toast?.classList.remove("show");
    }, 3000); // Duration in milliseconds (3 seconds)
  }

  toggleDropdown() { }

  getContactsList() {
    if (!localStorage.getItem('accessToken')) {
      return;
    }
    const body = { limit: 0, page: 0, exclude_hosts: 0 };
    this.apiService.contactsList(localStorage.getItem('accessToken') || '', body).subscribe(
      response => {
        this.contacts = response.contacts;
      },
      error => {
        console.log(error, 'ContactsListError==');
      }
    );
  }

  isRequestBodyValid(requestBody: any) {
    const keysToCheck = ['meeting_name', 'passcode', 'meeting_date', 'meeting_time', 'timezone', 'meeting_meridiem', 'hostusers', 'attend'];

    for (let key of keysToCheck) {
      if (Array.isArray(requestBody[key])) {
        // Check if the array is empty
        if (requestBody[key].length === 0) {
          return false;
        }
      } else {
        // Check if the string is empty
        if (requestBody[key] === '') {
          return false;
        }
      }
    }
    return true;
  }

  timeConvert(time: any[]): any {
    time = time.toString().match(/^([01]\d|2[0-3])(:)([0-5]\d)(:[0-5]\d)?$/) || [time];
    if (time.length > 1) {
      time = time.slice(1);
      time[5] = Number(time[0]) < 12 ? ' AM' : ' PM';
      time[0] = Number(time[0]) % 12 || 12;
      if (time[0] < 10) {
        time[0] = `0${Number(time[0]) % 12}` || 12;
      }
    }
    console.log(time);
    return time.join('');
  }

  inputChangeHandler(event: any): void {
    console.log(event)
    const { name, value } = event.target;
    console.log(value, 'value');
    if (name === 'meeting_date') {
      let date = value;
      date = date.split('-').reverse().join('-');
      this.requestBody[name] = date;
      return;
    }
    if (name === 'meeting_time') {
      const [time, meridiem] = this.timeConvert(value).split(' ');
      this.requestBody[name] = time;
      this.requestBody['meeting_meridiem'] = meridiem;
      return;
    }
    if (name === 'options') {
      console.log(this.requestBody)
      console.log('insideif==')
      const options = [value];
      if (!this.requestBody.options.includes(value)) {
        console.log('insideifif==', event)
        this.requestBody[name] = options;
        return;
      }
      options.shift();
      this.requestBody[name] = options;
      return;
    }
    this.requestBody[name] = value;
  }

  handleTimezoneInput(timezone: any) {
    this.requestBody["timezone"] = timezone;
  }

  isNotNumber(value: any): boolean {
    return typeof value !== 'number';
  }

  handleUserObject(event: any): void {
    const { name, value } = event.target;
    const val = value;
    this.userObject[name] = val;
  }

  addManualParticipant(): void {
    if (!this.userObject.first_name || !this.userObject.last_name || !this.userObject.email) {
      alert('Please set all the required fields');
      return
    }
    const attendParticipants = this.requestBody.attend ? [...this.requestBody.attend] : [];
    const participantCheck = attendParticipants.find((user: any) => user.email === this.userObject.email)
    if (!participantCheck) {
      attendParticipants.push({ ...this.userObject });
      this.requestBody.attend = attendParticipants;
    }
  }

  onSubmitHandler() {
    if (this.isRequestBodyValid(this.requestBody) === false) {
      alert('Please fill all the required fields');
      return
    }
    this.isScheduleLoading = true;
    const token = localStorage.getItem('accessToken') || "";
    this.apiService.scheduleMeeting(token, this.requestBody).subscribe(
      response => {
        if(response.success === false){
          alert(response.message);
          this.isScheduleLoading = false
          this.showToast("toast-failure");
          return
        }
        this.isScheduleLoading = false
        this.showToast("toast-success");
        this.showModal = true;
        localStorage.setItem('meetingId', response.data.meeting_id);
        this.roomName = response.data.meeting_id;
        this.passcode = response.data.passcode;
        this.joinURL = response.data.joinURL;

      },
      error => {
        console.error('Error:', error);
        this.isScheduleLoading = false;
        this.showToast("toast-failure");
      }
    )
  }

  instantMeeting() {
    this.isInstantLoading = true;
    const token = localStorage.getItem('accessToken') || "";
    const host = {
      first_name: "",
      last_name: "",
      email: ""
    };
    this.apiService.userDetails(
      localStorage.getItem('accessToken') || ''
    ).subscribe(response => {
      if(response.success === false) {
        alert(response.message);
        this.isInstantLoading = false;
        this.showToast("toast-failure");
        return
      }
      host.first_name = response.data.name?.split(' ')[0];
      host.last_name = response.data.name?.split(' ')[1];
      host.email = response.data.email;
      const body = {
        meeting_name: 'Quick Meeting',
        agenda: '',
        passcode: '123456',
        meeting_date: moment().format('DD-MM-YYYY'),
        meeting_time: moment().format('hh:mm'),
        meeting_meridiem: moment().format('h:mm a')
          .split(' ')[1].toUpperCase(),
        timezone: MomentTimezone.tz.guess(),
        instructions: 'Team call, join as soon as possible',
        is_show_portal: 1,
        options: ['ALLOW_GUEST', 'JOIN_ANYTIME'],
        hostusers: [host]
      };
      this.apiService.scheduleMeeting(token, body).subscribe(
        response => {
          console.log('Success:', response);
          if(response.success === false) {
            this.showToast("toast-failure");
            this.isInstantLoading = false;
            return
          }
          this.showToast("toast-success");
          this.isInstantLoading = false;
          this.showModal = true;
          localStorage.setItem('meetingId', response.data.meeting_id);
          this.roomName = response.data.meeting_id;
          this.passcode = response.data.passcode;
          this.joinURL = response.data.joinURL;
        },
        error => {
          console.error('Error:', error);
          this.showToast("toast-failure");
          this.isInstantLoading = false;
        }
      )
    }, error => {
      console.error(error);
      this.showToast("toast-failure");
    });

  }

  addParticipant(event?: any): void {
    console.log(event, 'event====')
    let participant = event.id;
    if (typeof participant !== 'number' && (!participant.first_name || !participant.last_name || !participant.email)) {
      alert('Please set all the required fields');
      return;
    }
    const attendParticipants = this.requestBody.attend ? [...this.requestBody.attend] : [];
    if (!attendParticipants.includes(participant)) {
      attendParticipants.push(participant);
      this.requestBody.attend = attendParticipants;
    }
    console.log(this.requestBody)
  }

  removeParticipant(participant: any): void {
    const existing = this.requestBody.attend ? [...this.requestBody.attend] : [];
    if (existing.length === 1) {
      existing.pop();
      this.requestBody.attend = existing;
      return;
    }
    existing.splice(existing.indexOf(participant), 1);
    this.requestBody.attend = existing;
  }

  addModerator(event: any): void {
    // const moderators = this.requestBody.hostusers ? [...this.requestBody.hostusers] : [];
    // if (!moderators.includes(moderator)) {
    //   moderators.push(moderator);
    //   this.requestBody.hostusers = moderators;
    // }

    let moderator = event.id;
    if (typeof moderator !== 'number' && (!moderator.first_name || !moderator.last_name || !moderator.email)) {
      alert('Please set all the required fields');
      return;
    }
    const moderators = this.requestBody.hostusers ? [...this.requestBody.hostusers] : [];
    if (!moderators.includes(moderator)) {
      moderators.push(moderator);
      this.requestBody.hostusers = moderators;
    }
  }

  removeModerator(moderator: any): void {
    const existing = this.requestBody.hostusers ? [...this.requestBody.hostusers] : [];
    if (existing.length === 1) {
      existing.pop();
      this.requestBody.hostusers = existing;
      return;
    }
    existing.splice(existing.indexOf(moderator), 1);
    this.requestBody.hostusers = existing;
  }

  closeModal() {
    this.showModal = false;
  }

  joinMeeting() {
    this.showModal = false;
    console.log(window.location, 'location')
    window.location.href = "/#/join-meeting"
  }
}

<div class="container">
  <div id="toast-container">
    <div id="toast-success" class="toast">Success</div>
    <div id="toast-failure" class="toast">Failure! Something went wrong.</div>
  </div>
  <!-- Modal -->
  <div class="modal-backdrop" *ngIf="showModal">
    <div class="modal">
      <div class="modal-header">
        <h2 class="modal-title">Meeting Overview</h2>
      </div>
      <div class="modal-body">
        <p>Meeting Id: {{roomName}}</p>
      </div>
      <div class="modal-body">
        <p>Passcode: {{passcode}}</p>
      </div>
      <div class="modal-body">
        <p>Join URL: {{joinURL}}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" (click)="joinMeeting()">Join Meeting</button>
        <button type="button" class="close" (click)="closeModal()">Close</button>
      </div>
    </div>
  </div>
  <div class="flex min-h-full items-center justify-center lg:w-[60%] pb-6 px-4 sm:px-3 lg:px-4 ml-3">
    <div>
      <form (ngSubmit)="onSubmitHandler()">
        <div>
          <h2 class="mt-2 text-center text-3xl font-bold tracking-tight text-gray-900">Schedule a meeting</h2>
        </div>
        <div class="mt-5">
          <input type="text" name="meeting_name" placeholder="Meeting Name" (input)="inputChangeHandler($event)" required>
        </div>
        <div>
          <input type="text" name="passcode" placeholder="Passcode" (input)="inputChangeHandler($event)" required>
        </div>
        <div>
          <input type="date" name="meeting_date" placeholder="Meeting Date" (input)="inputChangeHandler($event)" required>
        </div>
        <div>
          <input type="time" name="meeting_time" placeholder="Meeting Time" (input)="inputChangeHandler($event)" required>
        </div>
        <app-timezone [requestBody]="requestBody" (inputChange)="handleTimezoneInput($event)"></app-timezone>
        
        <!--Add Participants Dropdown-->
        <div>
          <h1 style="margin-top: 15px; font-size: large; font-weight: 600;">Add Participants</h1>
            <select [(ngModel)]="selectedParticipantContact" (ngModelChange)="addParticipant($event)" name="add-participants-contacts" style="width: 100%;" class="right-0 h-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none opacity-100 inline-flex w-full justify-between rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100">
              <option *ngFor="let contact of contacts" [ngValue]="contact">{{ contact.first_name }}</option>
            </select>
        </div>
        <div *ngFor="let user of requestBody.attend">
          <div *ngIf="isNotNumber(user)" class="flex justify-between">
            <h3>{{ user.first_name }}</h3>
            <button class="small-button"
              (click)="removeParticipant(user)"
            >
              Remove
            </button>
          </div>
        </div>
        <div *ngFor="let user of contacts">
          <div *ngIf="requestBody.attend.includes(user.id)" class="flex justify-between">
            <h3>{{ user.first_name }}</h3>
            <button
            class="small-button"
              (click)="removeParticipant(user.id)"
            >
              Remove
            </button>
          </div>
        </div>
  
        <!-- Add Participants Manually -->
  
        <form style="margin-top: 10px;">
          <h3>Add Participants Manually</h3>
          <div>
            <input type="text" name="first_name" placeholder="First Name" (input)="handleUserObject($event)" required>
          </div>
          <div>
            <input type="text" name="last_name" placeholder="Last Name" (input)="handleUserObject($event)" required>
          </div>
          <div>
            <input type="email" name="email" placeholder="Email" (input)="handleUserObject($event)" required>
          </div>
          <button (click)="addManualParticipant()" type="submit">Add</button>
        </form>
  
      <!--Add Moderators Dropdown-->
      <div>
        <h1 style="margin-top: 15px; font-size: large; font-weight: 600;">Add Moderators</h1>
        <select [(ngModel)]="selectedModeratorContact" (ngModelChange)="addModerator($event)" name="add-moderators-contacts" style="width: 100%;" class="right-0 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none opacity-100 inline-flex w-full justify-between rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100">
          <option *ngFor="let contact of contacts" [ngValue]="contact">{{ contact.first_name }}</option>
        </select>
      </div>
      
      <div style="margin-top: 10px;" *ngFor="let user of contacts">
        <div *ngIf="requestBody.hostusers.includes(user.id)" class="flex justify-between">
          <h3>{{ user.first_name }}</h3>
          <button
            class="small-button"
            (click)="removeModerator(user.id)"
          >
            Remove
          </button>
        </div>
      </div>
      <!-- Check Box -->
      <div>
        <p class="general-options-title">General Options</p>
        <div class="options-container">
          <div class="checkbox-container">
            <input
              (change)="inputChangeHandler($event)"
              id="options"
              name="options"
              type="checkbox"
              value="ALLOW_GUEST"
              class="checkbox"
            />
          </div>
          <div class="label-container">
            <label
              for="options"
              class="options-label"
            >
              Guest user can join meeting
            </label>
          </div>
        </div>
      </div>
        <div class="grid justify-content w-full">
          <button style="background-color: #7B1FA2;
        display: flex;
        justify-content: center; width: 100%;" type="submit">
          <div *ngIf="isScheduleLoading">
            <div class="loader"></div>
          </div>
          <p *ngIf="!isScheduleLoading">Schedule a meeting</p>
        </button>
        <h3>Or</h3>
        </div>
      </form>
      <button style="background-color: #1D4ED8;
        display: flex;
        justify-content: center;" (click)="instantMeeting()">
          <div *ngIf="isInstantLoading">
            <div class="loader"></div>
          </div>
          <p style="font-size: medium;" *ngIf="!isInstantLoading">Instant meeting</p>
        </button>
    </div>
    <!-- <button (click)="instantMeeting()">Start Instant Meeting</button> -->
  </div>
