// Web/Javascript/Angular/src/app/timezone/timezone.component.ts
import { CommonModule, NgFor } from '@angular/common';
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, ScheduleMeetingType } from 'angular-meethour';
import * as MomentTimezone from 'moment-timezone';

@Component({
  selector: 'app-timezone',
  templateUrl: './timezone.component.html',
  styleUrls: ['./timezone.component.css'],
  standalone: true,
  imports: [CommonModule, NgFor, FormsModule]
})
export class TimezoneComponent implements OnInit {
    @Input() requestBody: any = {
    meeting_name: '',
    passcode: '',
    meeting_date: '',
    meeting_time: '',
    timezone: '',
    instructions: '',
    is_show_portal: 1,
    options: [],
    hostusers: [],
    meeting_meridiem: '',
    attend: []
  };
  @Output() inputChange = new EventEmitter<any>();
  @Output() setRequestBody = new EventEmitter<any>();

  timezoneList: { value: string, name: string }[] = [];

  constructor(private apiService: ApiService) {
    this.requestBody = {
      meeting_name: '',
      passcode: '',
      meeting_date: '',
      meeting_time: '',
      timezone: '',
      instructions: '',
      is_show_portal: 1,
      options: [],
      hostusers: [],
      meeting_meridiem: '',
      attend: []
    };
  }

  async getTimezone() {
    this.apiService.timezone(localStorage.getItem('accessToken') || '').subscribe(
        response => {
          this.timezoneList = response.timezones;
          console.log(response);
          this.setRequestBody.emit({ ...this.requestBody, timezone: MomentTimezone.tz.guess() });
        },
        error => {
          console.error('Error:', error);
        }
      );
  }

  ngOnInit(): void {
    this.getTimezone();
  }

  onChange(event: any) {
    this.inputChange.emit(event.target.value);
  }
}

<div class="w-96 h-10 rounded-md mt-3">
    <select [value]="requestBody.timezone" (change)="onChange($event)" name="timezone" class="w-full h-full rounded-md focus:outline-none bg-slate-50 border border-slate-300">
      <option *ngFor="let timezone of timezoneList" [value]="timezone.value">{{ timezone.name }}</option>
    </select>
  </div>

// Web/Javascript/React/src/components/Timezone.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable max-len */
import ApiServices from 'meet-hour-react-web-sdk';
import MomentTimezone from 'moment-timezone';
import React, { useEffect, useState } from 'react';

/**
 @param {any} inputChangeHandler
 @param {any} requestBody
 @param {any} setRequestBody
 */
function Timezone({ inputChangeHandler, requestBody, setRequestBody }: { inputChangeHandler: (value: any) => void; requestBody: any; setRequestBody: (value: any) => void; }) {
    const [ timezoneList, setTimezoneList ] = useState<[]>();
    const getTimezone = async () => {
        const response = await ApiServices.timezone(localStorage.getItem('accessToken') || '');
        setTimezoneList(response.timezones);
        setRequestBody({ ...requestBody,
            timezone: MomentTimezone.tz.guess() });
    };

    useEffect(() => {
        getTimezone();
    }, []);

    return (
        <div className='w-full h-10 rounded-md'>
            <select value={requestBody.timezone} className='w-full h-full rounded-md focus:outline-none bg-slate-50 border border-slate-300' name="timezone" onChange={(inputChangeHandler)}>
                {timezoneList?.map((timezone: any) =>
                    <option key={timezone.value} className='w-96' value={timezone.value}>{timezone.name}</option>
                )}
            </select>
        </div>
    );
}

export default Timezone;
